services:
  notion-intelligence:
    image: ghcr.io/nekketsu-git/notion-intelligence:latest
    container_name: notion-intelligence
    env_file:
      - .env.prod
    volumes:
      - chroma-data:/data/chroma
      - agent-log:/data/agent_log

volumes:
  chroma-data:
    driver: local
  agent-log:
    driver: local
